### ISSUE TITLE
List index out of range & Could not find settings

### ISSUE THREAD

**Issue by itsyxo** [vivinano/MudaeAutoBot#230]
```
Reading from File for channel 1085583803688431686
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000243CC5CF350>>
Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python311\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Noah\Downloads\MudaeAutoBot-main\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\Downloads\MudaeAutoBot-main\MudaeAutoBot-4\MudaeAutoBot.py", line 223, in parse_settings_message
    settings['prefix'] = val_parse(settings_p[0])[0]
                         ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-03-16 11:59:56,911:Could not find settings for 1085583803688431686, please trigger the '$settings' command in the server and run the bot again.
2023-03-16 12:00:03,529:Could not find settings for 1085583803688431686, please trigger the '$settings' command in the server and run the bot again.
2023-03-16 12:06:21,729:Could not find settings for 1080249172025937970, please trigger the '$settings' command in the server and run the bot again.
```
I just dont know what to do atp

**Comment by vivinano** [comment]
Do you have a $settings instance in the channels you are using Sent from my iPhoneOn Mar 16, 2023, at 7:06 AM, itsyxo ***@***.***> wrote:﻿
Reading from File for channel 1085583803688431686
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000243CC5CF350>>
Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python311\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Noah\Downloads\MudaeAutoBot-main\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\Downloads\MudaeAutoBot-main\MudaeAutoBot-4\MudaeAutoBot.py", line 223, in parse_settings_message
    settings['prefix'] = val_parse(settings_p[0])[0]
                         ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-03-16 11:59:56,911:Could not find settings for 1085583803688431686, please trigger the '$settings' command in the server and run the bot again.
2023-03-16 12:00:03,529:Could not find settings for 1085583803688431686, please trigger the '$settings' command in the server and run the bot again.
2023-03-16 12:06:21,729:Could not find settings for 1080249172025937970, please trigger the '$settings' command in the server and run the bot again.

I just dont know what to do atp

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by vivinano** [comment]
You could manually copy it and paste it as a txt document in the channeldata folder and rename is the channelid Sent from my iPhoneOn Mar 16, 2023, at 12:50 PM, itsyxo ***@***.***> wrote:﻿
Even tho the $settings is in the chat it still say the error when a message is sent

**Comment by itsyxo** [comment]
i fixed the error with the settings but now i still remain with the IndexError: list index out of range
![image](https://user-images.githubusercontent.com/81576629/225718004-c64a6844-e8ce-48f5-90a7-e083e111270f.png)

**Comment by vivinano** [comment]
If you do the manual copy and paste please add the * (bold) marks Sent from my iPhoneOn Mar 16, 2023, at 2:27 PM, itsyxo ***@***.***> wrote:﻿
i fixed the error with the settings but now i still remain with the IndexError: list index out of range

**Comment by itsyxo** [comment]
i have the bolds marks but it still doesnt resolve my issues (still ty for helping me :') )
